### ISSUE TITLE
error running app

### ISSUE THREAD

**Issue by qinyang39** [phrasenmaeher/audio-transformation-visualization#1]
Hey there,
I have huge interest on your audio transformation visualization but failed to open the streamlit.
Could you please tell me any thing I can try?

Thanks in advance.

**Comment by phrasenmaeher** [comment]
Hi, thanks for your interest! I've noticed the problem and am working on it. Until I have included information to run the project locally, you can try the online version: https://share.streamlit.io/phrasenmaeher/audio-transformation-visualization/main/visualize_transformation.py (which should be fixed soon)

**Comment by qinyang39** [comment]
Hi, it works now. Thank you so much!!
