### ISSUE TITLE
The link is broken.  (https://share.streamlit.io/phrasenmaeher/audio-transformation-visualization/main/visualize_transformation.py)

### ISSUE THREAD

**Issue by JJs-fun-stuff** [phrasenmaeher/audio-transformation-visualization#3]

**Comment by phrasenmaeher** [comment]
Thanks for taking the time to notify me about the issue! 
I have rebooted the application and it's now running fine again.
If the error re-appears--over the long run--I'll refactor the code.

**Comment by JJs-fun-stuff** [comment]
Thank you. What a quick response!
